# Education Project: Socioeconomic Factors Associated with ACT Scores

## Data Preparation before analysis

In [1]:
# Import pandas, numpy, and matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# seaborn is a data visualization library built on matplotlib
import seaborn as sns

# set the plotting style
sns.set_style("whitegrid")

Load Edgap dataset

In [2]:
# Here, we read the school ID as an object because it is an identifier, not a numerical measurement.
edgap = pd.read_excel('C:/Users/binay/Documents/data5100/projects/education/data/EdGap_data.xlsx',
                     dtype = {'NCESSCH School ID': object})

C:\Users\binay\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

In [3]:
edgap.info()

<class 'pandas.DataFrame'>
RangeIndex: 7986 entries, 0 to 7985
Data columns (total 7 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   NCESSCH School ID                                7986 non-null   object
 1   CT Unemployment Rate                             7972 non-null   float64
 2   CT Pct Adults with College Degree                7973 non-null   float64
 3   CT Pct Childre In Married Couple Family          7961 non-null   float64
 4   CT Median Household Income                       7966 non-null   float64
 5   School ACT average (or equivalent if SAT score)  7986 non-null   float64
 6   School Pct Free and Reduced Lunch                7986 non-null   float64
dtypes: float64(6), object(1)
memory usage: 436.9+ KB

Key items to note from the Edgap dataset:
* Unemployment Rate could be used as predictor
* Percent adults with college degree as predictor
* Percent children in married family as predictor
* Median Household Income as predictor
* ACT average --> This is what we would like to predict. Dependent variable
* Percent of students receiving Free and reduced lunch as predictor
* Missing value --> Some missing value that needs to be addressed
* Data type --> We have addressed School Id. Rest seems to be fine.

Load school information data

In [4]:
# We specify the encoding here so Python can correctly read the characters in this CSV file.
school_information = pd.read_csv('C:/Users/binay/Documents/data5100/projects/education/data/ccd_sch_029_1617_w_1a_11212017.csv',
                                encoding = 'unicode_escape')

C:\Users\binay\AppData\Local\Temp\ipykernel_27168\947730268.py:2: DtypeWarning: Columns (0: STATE_AGENCY_NO, 1: LEAID, 2: MSTREET2, 3: MSTREET3, 4: MZIP, 5: MZIP4, 6: LSTREET2, 7: LSTREET3, 8: LZIP, 9: LZIP4, 10: SY_STATUS, 11: UPDATED_STATUS, 12: SCH_TYPE, 13: CHARTAUTH1, 14: CHARTAUTH2, 15: CHARTAUTHN2) have mixed types. Specify dtype option on import or set low_memory=False.
  school_information = pd.read_csv('C:/Users/binay/Documents/data5100/projects/education/data/ccd_sch_029_1617_w_1a_11212017.csv',

In [5]:
school_information.info()

<class 'pandas.DataFrame'>
RangeIndex: 102183 entries, 0 to 102182
Data columns (total 65 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   SCHOOL_YEAR          102183 non-null  str
 1   FIPST                102183 non-null  int64
 2   STATENAME            102183 non-null  str
 3   ST                   102183 non-null  str
 4   SCH_NAME             102183 non-null  str
 5   LEA_NAME             102183 non-null  str
 6   STATE_AGENCY_NO      102183 non-null  object
 7   UNION                2533 non-null    float64
 8   ST_LEAID             102183 non-null  str
 9   LEAID                102183 non-null  object
 10  ST_SCHID             102183 non-null  str
 11  NCESSCH              102181 non-null  float64
 12  SCHID                102181 non-null  float64
 13  MSTREET1             102181 non-null  str
 14  MSTREET2             1825 non-null    str
 15  MSTREET3             28 non-null      str
 16  MCITY                102183 non-null  str
 17  MSTATE               102183 non-null  str
 18  MZIP                 102183 non-null  object
 19  MZIP4                60419 non-null   object
 20  LSTREET1             102183 non-null  str
 21  LSTREET2             582 non-null     str
 22  LSTREET3             13 non-null      str
 23  LCITY                102183 non-null  str
 24  LSTATE               102183 non-null  str
 25  LZIP                 102183 non-null  object
 26  LZIP4                59145 non-null   object
 27  PHONE                102183 non-null  str
 28  WEBSITE              51983 non-null   str
 29  SY_STATUS            102181 non-null  object
 30  SY_STATUS_TEXT       102181 non-null  str
 31  UPDATED_STATUS       102181 non-null  object
 32  UPDATED_STATUS_TEXT  102181 non-null  str
 33  EFFECTIVE_DATE       102181 non-null  str
 34  SCH_TYPE_TEXT        102181 non-null  str
 35  SCH_TYPE             102181 non-null  object
 36  RECON_STATUS         102181 non-null  str
 37  OUT_OF_STATE_FLAG    102179 non-null  str
 38  CHARTER_TEXT         102179 non-null  str
 39  CHARTAUTH1           6687 non-null    object
 40  CHARTAUTHN1          6687 non-null    str
 41  CHARTAUTH2           116 non-null     object
 42  CHARTAUTHN2          116 non-null     str
 43  NOGRADES             102179 non-null  str
 44  G_PK_OFFERED         102179 non-null  str
 45  G_KG_OFFERED         102179 non-null  str
 46  G_1_OFFERED          102179 non-null  str
 47  G_2_OFFERED          102179 non-null  str
 48  G_3_OFFERED          102179 non-null  str
 49  G_4_OFFERED          102179 non-null  str
 50  G_5_OFFERED          102179 non-null  str
 51  G_6_OFFERED          102179 non-null  str
 52  G_7_OFFERED          102179 non-null  str
 53  G_8_OFFERED          102179 non-null  str
 54  G_9_OFFERED          102179 non-null  str
 55  G_10_OFFERED         102179 non-null  str
 56  G_11_OFFERED         102179 non-null  str
 57  G_12_OFFERED         102179 non-null  str
 58  G_13_OFFERED         102179 non-null  str
 59  G_UG_OFFERED         102179 non-null  str
 60  G_AE_OFFERED         102179 non-null  str
 61  GSLO                 102179 non-null  str
 62  GSHI                 102179 non-null  str
 63  LEVEL                102179 non-null  str
 64  IGOFFERED            102179 non-null  str
dtypes: float64(3), int64(1), object(11), str(50)
memory usage: 78.6+ MB

In summary this dataset contains a lot of reference information about school. 
Key items to note from school information dataset:
* Volume of dataset. This dataset contains a significant number of columns and rows.
* It means Edgap dataset does not contain information for all schools listed in the school information dataset.
* We will be interested in descriptive values in columns LEVEL, CHARTER_TEXT.
* Additionally Geo location data points like STATE, CITY may be useful.
* Missing Values --> There are missing values. We would be interested in knowing if any data that needed to be joind with Edgap is missing. 
* Additional review is needed to understand relevant datapoints for analysis.

In [6]:
school_information.head(5)

,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,LEA_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,...,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED
0,2016-2017,1,ALABAMA,AL,Sequoyah Sch - Chalkville Campus,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported
1,2016-2017,1,ALABAMA,AL,Camps,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported
2,2016-2017,1,ALABAMA,AL,Det Ctr,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported
3,2016-2017,1,ALABAMA,AL,Wallace Sch - Mt Meigs Campus,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported
4,2016-2017,1,ALABAMA,AL,McNeel Sch - Vacca Campus,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported

Since we can not see all columns when we look at the .head(), we can update the default option so we can display all columns.

In [7]:
pd.set_option('display.max_columns', None)
school_information.head()

,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,LEA_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,NCESSCH,SCHID,MSTREET1,MSTREET2,MSTREET3,MCITY,MSTATE,MZIP,MZIP4,LSTREET1,LSTREET2,LSTREET3,LCITY,LSTATE,LZIP,LZIP4,PHONE,WEBSITE,SY_STATUS,SY_STATUS_TEXT,UPDATED_STATUS,UPDATED_STATUS_TEXT,EFFECTIVE_DATE,SCH_TYPE_TEXT,SCH_TYPE,RECON_STATUS,OUT_OF_STATE_FLAG,CHARTER_TEXT,CHARTAUTH1,CHARTAUTHN1,CHARTAUTH2,CHARTAUTHN2,NOGRADES,G_PK_OFFERED,G_KG_OFFERED,G_1_OFFERED,G_2_OFFERED,G_3_OFFERED,G_4_OFFERED,G_5_OFFERED,G_6_OFFERED,G_7_OFFERED,G_8_OFFERED,G_9_OFFERED,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED
0,2016-2017,1,ALABAMA,AL,Sequoyah Sch - Chalkville Campus,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0020,1.000020e+10,100277.0,P O Box 9486,NaN,NaN,Birmingham,AL,35220,NaN,1000 Industrial School Road,NaN,NaN,Birmingham,AL,35220,NaN,(205)680-8574,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported
1,2016-2017,1,ALABAMA,AL,Camps,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0050,1.000020e+10,101667.0,P O Box 66,NaN,NaN,Mt Meigs,AL,36057,NaN,1601 County Rd. 57,NaN,NaN,Prattville,AL,36067,NaN,(334)215-3850,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported
2,2016-2017,1,ALABAMA,AL,Det Ctr,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0060,1.000020e+10,101670.0,P O Box 66,NaN,NaN,Mt Meigs,AL,36057,NaN,2109 Bashi Rd Bldg 509,NaN,NaN,Thomasville,AL,36784,NaN,(334)215-3850,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported
3,2016-2017,1,ALABAMA,AL,Wallace Sch - Mt Meigs Campus,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0030,1.000020e+10,101705.0,P O Box 66,NaN,NaN,Mount Meigs,AL,36057,NaN,1000 Industrial School Road,NaN,NaN,Mount Meigs,AL,36057,NaN,(334)215-6039,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported
4,2016-2017,1,ALABAMA,AL,McNeel Sch - Vacca Campus,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0040,1.000020e+10,101706.0,8950 Roebuck Blvd,NaN,NaN,Birmingham,AL,35206,NaN,8950 Roebuck Blvd,NaN,NaN,Birmingham,AL,35206,NaN,(205)838-4981,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported

In [8]:
school_information.columns

Index(['SCHOOL_YEAR', 'FIPST', 'STATENAME', 'ST', 'SCH_NAME', 'LEA_NAME',
       'STATE_AGENCY_NO', 'UNION', 'ST_LEAID', 'LEAID', 'ST_SCHID', 'NCESSCH',
       'SCHID', 'MSTREET1', 'MSTREET2', 'MSTREET3', 'MCITY', 'MSTATE', 'MZIP',
       'MZIP4', 'LSTREET1', 'LSTREET2', 'LSTREET3', 'LCITY', 'LSTATE', 'LZIP',
       'LZIP4', 'PHONE', 'WEBSITE', 'SY_STATUS', 'SY_STATUS_TEXT',
       'UPDATED_STATUS', 'UPDATED_STATUS_TEXT', 'EFFECTIVE_DATE',
       'SCH_TYPE_TEXT', 'SCH_TYPE', 'RECON_STATUS', 'OUT_OF_STATE_FLAG',
       'CHARTER_TEXT', 'CHARTAUTH1', 'CHARTAUTHN1', 'CHARTAUTH2',
       'CHARTAUTHN2', 'NOGRADES', 'G_PK_OFFERED', 'G_KG_OFFERED',
       'G_1_OFFERED', 'G_2_OFFERED', 'G_3_OFFERED', 'G_4_OFFERED',
       'G_5_OFFERED', 'G_6_OFFERED', 'G_7_OFFERED', 'G_8_OFFERED',
       'G_9_OFFERED', 'G_10_OFFERED', 'G_11_OFFERED', 'G_12_OFFERED',
       'G_13_OFFERED', 'G_UG_OFFERED', 'G_AE_OFFERED', 'GSLO', 'GSHI', 'LEVEL',
       'IGOFFERED'],
      dtype='str')

In [9]:
school_information = school_information[['SCHOOL_YEAR', 'NCESSCH', 'LSTATE', 'LZIP', 'SCH_TYPE_TEXT', 'LEVEL', 'CHARTER_TEXT', 'G_12_OFFERED']] # CHARTER_TEXT attribute is missing

In [10]:
school_information

,SCHOOL_YEAR,NCESSCH,LSTATE,LZIP,SCH_TYPE_TEXT,LEVEL,CHARTER_TEXT,G_12_OFFERED
0,2016-2017,1.000020e+10,AL,35220,Alternative School,High,No,Yes
1,2016-2017,1.000020e+10,AL,36067,Alternative School,High,No,Yes
2,2016-2017,1.000020e+10,AL,36784,Alternative School,High,No,Yes
3,2016-2017,1.000020e+10,AL,36057,Alternative School,High,No,Yes
4,2016-2017,1.000020e+10,AL,35206,Alternative School,High,No,Yes
...,...,...,...,...,...,...,...,...
102178,2016-2017,7.800030e+11,VI,802,Regular School,Elementary,Not applicable,No
102179,2016-2017,7.800030e+11,VI,802,Regular School,Elementary,Not applicable,No
102180,2016-2017,7.800030e+11,VI,802,Regular School,Elementary,Not applicable,No
102181,2016-2017,7.800030e+11,VI,804,Regular School,Middle,Not applicable,No
102182,2016-2017,7.800030e+11,VI,802,Regular School,Middle,Not applicable,No

In [11]:
edgap.columns

Index(['NCESSCH School ID', 'CT Unemployment Rate',
       'CT Pct Adults with College Degree',
       'CT Pct Childre In Married Couple Family', 'CT Median Household Income',
       'School ACT average (or equivalent if SAT score)',
       'School Pct Free and Reduced Lunch'],
      dtype='str')

In [13]:
school_information.columns

Index(['SCHOOL_YEAR', 'NCESSCH', 'LSTATE', 'LZIP', 'SCH_TYPE_TEXT', 'LEVEL',
       'CHARTER_TEXT', 'G_12_OFFERED'],
      dtype='str')

### Rename Columns

In [12]:
edgap = edgap.rename(
    columns={'NCESSCH School ID': 'id', 
             'CT Pct Adults with College Degree': 'percent_college' ,
             'CT Unemployment Rate': 'rate_unemployment' ,
             'CT Pct Childre In Married Couple Family': 'percent_married', 
             'CT Median Household Income':'median_income',
             'School ACT average (or equivalent if SAT score)':'average_act',
             'School Pct Free and Reduced Lunch':'percent_lunch',
            })

In [14]:
school_information = school_information.rename(
    columns={ 'SCHOOL_YEAR': 'year', 
              'NCESSCH': 'id', 
              'LSTATE': 'state', 
              'LZIP': 'zip_code', 
              'SCH_TYPE_TEXT': 'school_type', 
              'LEVEL': 'school_level',
              'CHARTER_TEXT': 'charter',
              'G_12_OFFERED': 'grade_12_offered',# MISSING THIS ATTRIBUTE
})

In [15]:
edgap.info()

<class 'pandas.DataFrame'>
RangeIndex: 7986 entries, 0 to 7985
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 7986 non-null   object
 1   rate_unemployment  7972 non-null   float64
 2   percent_college    7973 non-null   float64
 3   percent_married    7961 non-null   float64
 4   median_income      7966 non-null   float64
 5   average_act        7986 non-null   float64
 6   percent_lunch      7986 non-null   float64
dtypes: float64(6), object(1)
memory usage: 436.9+ KB

In [16]:
school_information.info()

<class 'pandas.DataFrame'>
RangeIndex: 102183 entries, 0 to 102182
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   year              102183 non-null  str
 1   id                102181 non-null  float64
 2   state             102183 non-null  str
 3   zip_code          102183 non-null  object
 4   school_type       102181 non-null  str
 5   school_level      102179 non-null  str
 6   charter           102179 non-null  str
 7   grade_12_offered  102179 non-null  str
dtypes: float64(1), object(1), str(6)
memory usage: 10.1+ MB

## Exploratory Data Analysis

## Simple linear regression
Examine two socioeconomic predictors individually.

## Multiple linear regression
Use several predictors together to understand their relationships with ACT scores.

## Categorical analysis
tbd